// Development user profile
const DEV_USER_PROFILE = {
  id: "dev-user-123",
  first_name: "Dev",
  last_name: "User",
  email: "dev@dharmasaathi.com",
  mobile_number: "+91-9999999999",
  mobile_verified: true,
  email_verified: true,
  gender: "Male",
  birthdate: "1990-01-01",
  city: "Mumbai",
  state: "Maharashtra",
  country: "India",
  mother_tongue: "Hindi",
  education: "B.Tech",
  profession: "Software Developer",
  diet: "Vegetarian",
  about_me: "Development test user for DharmaSaathi",
  spiritual_org: ["Art of Living", "Isha Foundation"],
  daily_practices: ["Meditation", "Yoga"],
  user_photos: ["/abstract-spiritual-avatar-1.png"],
  verification_status: "verified",
  account_status: "sangam",
  onboarding_completed: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  partner_age_min: 25,
  partner_age_max: 35,
  partner_location_preference: "same_state",
}

export { DEV_USER_PROFILE }
