-- Insert sample users
INSERT INTO users (
  id, name, age, city, photos, about_me, spiritual_highlights, 
  spiritual_journey, partner_expectations, occupation, education, 
  height, religion, mother_tongue, kyc_verified, is_premium
) VALUES 
(
  '550e8400-e29b-41d4-a716-446655440001',
  'Priya Sharma',
  28,
  'Mumbai',
  ARRAY['https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400'],
  'A spiritual seeker who finds peace in meditation and yoga. I believe in living a life of compassion and mindfulness.',
  ARRAY['Daily Meditation', 'Yoga Practitioner', 'Vegetarian', 'Temple Volunteer'],
  'My spiritual journey began in college when I started practicing yoga. Over the years, meditation has become my anchor, helping me navigate life with greater awareness and peace.',
  'Looking for someone who shares similar spiritual values and believes in growing together on this beautiful journey of life.',
  'Software Engineer',
  'B.Tech Computer Science',
  '5''4"',
  'Hindu',
  'Hindi',
  true,
  false
),
(
  '550e8400-e29b-41d4-a716-446655440002',
  'Arjun Patel',
  32,
  'Ahmedabad',
  ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400'],
  'Devoted to dharma and seeking a life partner who values spiritual growth and family traditions.',
  ARRAY['Bhagavad Gita Study', 'Morning Prayers', 'Ayurveda Enthusiast', 'Classical Music'],
  'Raised in a traditional family, I have always been drawn to our ancient wisdom. I practice daily meditation and find solace in reading spiritual texts.',
  'Seeking a partner who values our cultural heritage and is interested in building a spiritually grounded family.',
  'Business Owner',
  'MBA',
  '5''10"',
  'Hindu',
  'Gujarati',
  true,
  true
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  'Ananya Reddy',
  26,
  'Hyderabad',
  ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400'],
  'Believer in the power of positive thinking and spiritual healing. Love spending time in nature and practicing mindfulness.',
  ARRAY['Reiki Healer', 'Nature Lover', 'Mindfulness', 'Organic Living'],
  'My spiritual path led me to become a certified Reiki healer. I believe in the interconnectedness of all beings and practice compassion in daily life.',
  'Looking for a soulmate who appreciates holistic living and wants to create a harmonious life together.',
  'Wellness Coach',
  'M.Sc Psychology',
  '5''6"',
  'Hindu',
  'Telugu',
  false,
  false
);
